# golangci-lint v1 configuration
# This configuration enables linters to ensure code quality.

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - contextcheck
    - dupl          # Code duplication detection
    - gocyclo       # Cyclomatic complexity
    - gocritic      # Code critique and code smells
    - goconst       # Constant usage
    - gocognit      # Cognitive complexity

linters-settings:
  dupl:
    threshold: 150
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - hugeParam
      - rangeValCopy
      - unnamedResult
      - httpNoBody
      - exitAfterDefer
  goconst:
    min-len: 3
  gocognit:
    min-complexity: 15

issues:
  exclude-rules:
    # Exclude test files from some checks
    - path: _test\.go
      linters:
        - dupl
        - goconst
