#!/usr/bin/env bash
# Idempotent: create repo-root .env.dev with CYNODE_SECURE_STORE_MASTER_KEY_B64 if missing.
# Used by scripts/justfile (setup-dev start, component node-manager start). .env* is gitignored.
set -euo pipefail

root="${1:?repository root required}"

if [ -f "$root/.env.dev" ]; then
  exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "[ERROR] openssl not found; cannot create $root/.env.dev (need openssl rand -base64 32)." >&2
  exit 1
fi

key="$(openssl rand -base64 32)"
umask 077
{
  echo "# Generated by CyNodeAI scripts/ensure_env_dev.sh (setup-dev). Local only; gitignored (.env*)."
  echo "export CYNODE_SECURE_STORE_MASTER_KEY_B64='${key}'"
} >"$root/.env.dev"
chmod 600 "$root/.env.dev" 2>/dev/null || true
echo "[INFO] Created $root/.env.dev with a random secure-store master key for local dev."
echo "[INFO] Optional vars: see $root/.env.example (NATS_DEV_* seeds, JWT, PSK, …)."
